# This is configuration file for Palcord utility,
# edit PalWorldSettings.yaml if you want to configure Palworld settings.

# Token to control Discord Bot
# Token can obtained by creating bot on Discord Developer Portal
# (https://discord.com/developers/applications).
# If "", no or false is set, this function will be disabled.
DiscordBOT-Token: ""  # TODO: Put your token

# ID of Channel where Channel Topic is updated to latest server info
# If "", no or false is set, this function will be disabled.
IPNotify-ChannelID: ""
# Configure contents of Channel Topic
# The following placeholders are available:
# %IP% : Server Global IP Address
# %PASSWORD% : Server Password (read from PalWorldSettings-ini-Path)
# %PLAYERNUM% : Number of players
# %REGISTERNUM% : Number of people who register as player on Discord
# %PLAYERMAXNUM% : # Maximum number of players that can join the server (read from PalWorldSettings-ini-Path)
ChannelTopic-Content: "IP: %IP%  Pass: %PASSWORD%  %PLAYERNUM%/%REGISTERNUM% Online"

# ID of channel where server console will be available
# If "", no or false is set, this function will be disabled.
ServerConsole-ChannelID: ""

# Enable to kick players who haven't registered as player on Discord
Kick-UnregisteredPlayers: false

# Enable you to configure server settings by editing PalWorldSettings.yaml instead of PalWorldSettings.ini
Enable-PalWorldSettings-yaml: true
# Path to YAML settings file (PalWorldSettings.yaml)
# You can specify absolute-path or relative-path from this file.
# You don't have to change this value normally.
PalWorldSettings-yaml-Path: "./PalWorldSettings.yaml"
# Path to Original settings file (PalWorldSettings.ini)
# You can specify absolute-path or relative-path from this file.
PalWorldSettings-ini-Path: "~/steamapps/common/PalServer/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini"